#!/bin/bash

# This script is autogenerated by Ansible to run the Julia package generation playbook.
ansible-playbook -i $HOME/.gap/PackageJanitor/gap_to_julia/hosts $HOME/.gap/PackageJanitor/gap_to_julia/site.yml -l ToolsForCategoricalTowers --diff "$@" < /dev/null
